version: "3.8"
services:
    app:
        build:
            context: ./docker/php
        container_name: auto-saas-app
        volumes:
            - ./src:/var/www
        working_dir: /var/www
        depends_on:
            - mysql
        networks:
            - appnet

    web:
        image: nginx:alpine
        container_name: auto-saas-web
        ports:
            - "8000:80"
        volumes:
            - ./src:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - appnet

    mysql:
        image: mysql:8
        container_name: auto-saas-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: auto_saas
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - appnet

    redis:
        image: redis:alpine
        container_name: auto-saas-redis
        ports:
            - "6379:6379"
        networks:
            - appnet

volumes:
    dbdata:

networks:
    appnet:
